In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.svm import SVR, SVC
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NeighborhoodComponentsAnalysis
from sklearn.linear_model import LassoCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [4]:
#load the features
features_df = pd.read_csv("/Users/folasewaabdulsalam/Downloads/EEG_Based_Mental_Workload_Classifier/EEG-Based_Mental_Workload_Classifier/features.csv")
print(f"The Features shape:{features_df.shape}")
features_df.head(5)

The Features shape:(93, 58)

     delta_AF3    delta_F7    delta_F3  ...   beta_AF4  subject  workload
0    10.725343    5.077131    2.238050  ...   0.879012    sub01        hi
1  5516.791766  963.839271  128.723981  ...  14.620083    sub01        lo
2     3.989949    2.608310    1.053837  ...   0.551459    sub02        hi
3     2.253481    0.975757    0.694703  ...   0.281283    sub02        lo
4    55.389697    9.962111    4.743549  ...   0.462703    sub03        hi

[5 rows x 58 columns]

In [5]:
#load and merge ratings
ratings = pd.read_csv("/Users/folasewaabdulsalam/Downloads/EEG_Based_Mental_Workload_Classifier/EEG-Based_Mental_Workload_Classifier/ratings.txt", header=None, names=['subject', 'rating_low', 'rating_high'])
#create subject mapping to align with our features dataframe 1 → 'sub01'

subject_mapping = {i: f'sub{i:02d}' for i in range(1,49)}
ratings['subject'] = ratings['subject'].replace(subject_mapping)
print(ratings.head())

  subject  rating_low  rating_high
0   sub01           2            8
1   sub02           1            5
2   sub03           1            5
3   sub04           2            5
4   sub06           4            7

In [8]:
#merging the two datasets

#prepare the ratings in long format
ratings_long = []

for _, row in ratings.iterrows():
    ratings_long.append(
        {'subject': row['subject'], 'workload': 'lo', 'rating': row['rating_low']} #low workload ratings

    )
    ratings_long.append(
        {'subject': row['subject'], 'workload': 'hi', 'rating':row['rating_high']} #high workload ratings
    )
ratings_df = pd.DataFrame(ratings_long)
ratings_df.head()

#merging the long format of the ratings text with the features


data = features_df.merge(ratings_df, on=['subject', 'workload'], how='inner')

print(f"\nMerged data shape: {data.shape}")
print(data['rating'].value_counts().sort_index())
data.head()

Merged data shape: (87, 59)
rating
1    23
2    11
3     7
4     5
5    11
6     6
7    11
8    10
9     3
Name: count, dtype: int64

     delta_AF3    delta_F7    delta_F3  ...  subject  workload  rating
0    10.725343    5.077131    2.238050  ...    sub01        hi       8
1  5516.791766  963.839271  128.723981  ...    sub01        lo       2
2     3.989949    2.608310    1.053837  ...    sub02        hi       5
3     2.253481    0.975757    0.694703  ...    sub02        lo       1
4    55.389697    9.962111    4.743549  ...    sub03        hi       5

[5 rows x 59 columns]